num_niches: 5 # per feature/measure dimension
num_generations: 100000 # 180000
num_emitters: 128
mu: 0.0
sigma: 1.0
learning_rate: 0.5 # 0.01
output_inv_frequency: 1000
batch_size: 8

# SAIL configuration
lambda_ucb: 1.0
surrogate_update_frequency: 1000
surrogate_num_init_samples: 128
surrogate_num_samples: 8
surrogate_num_epochs: 2000
